### ISSUE TITLE
Prompt or questions

### ISSUE THREAD

**Issue by Phakeme** [KaylaKremer/CoderbyteReact#3]
Can you please maybe add Prompts or questions to every solution?
It would be great to have both questions and answers for beginners like me.

**Comment by KaylaKremer** [comment]
Hello!

Thank you for the suggestion! Unfortunately, I can't include the prompts/questions as that would violate Coderbyte's Terms of Use:

> Don't Copy From Us. You agree not to modify, copy, frame, imitate, mirror, reproduce, distribute, publish, download, display, perform, post, store, or transmit any of content made available through the Site, including without limitation any marks, in any form or by any means, including but not limited to electronic, mechanical, photocopying, recording, or otherwise. You agree not to rent, lease, loan, sell, distribute or create derivative works based on the Site, in whole or in part, except that the foregoing does not apply to your own User Content that you legally uploaded to the Site.

My solutions are only meant as a resource to check against your own or just to study from in general! You'll need to pay for Coderbyte to see their code challenges.
